version 2.0.1

diff --git a/inst/gitlab-ci/bookdown-production.yml b/inst/gitlab-ci/bookdown-production.yml
--- a/inst/gitlab-ci/bookdown-production.yml
+++ b/inst/gitlab-ci/bookdown-production.yml
@@ -3,53 +3,49 @@ image: {image}
 variables:
   GIT_DEPTH: 10
   REPO_NAME: "{repo_name}"
-  R_LIBS: "ci/lib"
+  R_LIBS_USER: "ci/lib"
 
 cache:
   key: global-cache
   paths:
-      - ${R_LIBS}
+      - ${R_LIBS_USER}
 
 stages:
-  - install-deps
   - book-create
   - deploy
 
-installation:
-    stage: install-deps
+book-branch:
+    stage: book-create
+    except:
+        - main
+        - master
+        - production
+        - merge_requests
     script:
-        - echo "Library path for packages :" $R_LIBS
-        - mkdir -p $R_LIBS
+        - if [[ $CI_DEFAULT_BRANCH == "master" || $CI_DEFAULT_BRANCH = "main" ]]; then echo "OK - Default branch is master or main"; else echo "Default branch is not master or main; please add yours ($CI_DEFAULT_BRANCH) where needed, as well as in the present line of code" ; exit 1; fi
+        - echo "Library path for packages :" $R_LIBS_USER
+        - mkdir -p $R_LIBS_USER
         - Rscript -e 'install.packages(c("remotes", "attachment", "tinytex", "usethis"))'
         - Rscript -e 'if (!file.exists("DESCRIPTION")) {usethis::use_description()}'
-        - Rscript -e 'imports <- unique(c("bookdown", "knitr", attachment::att_from_rmds(".", recursive = FALSE)));attachment::att_to_desc_from_is(path.d = "DESCRIPTION", imports = imports)'
-        - Rscript -e 'remotes::install_deps(dependencies = TRUE)'
-        
-book-production:
-    stage: book-create
-    only:
-        - production
-    script:
-        - echo "Library path for packages :" $R_LIBS
-        - mkdir -p $R_LIBS
+        - >
+          Rscript -e 'imports <- unique(c("bookdown", "knitr", "pagedown",
+            attachment::att_from_rmds(".", recursive = FALSE)));
+            if (packageVersion("attachment") <= "0.2.2") {
+              attachment::att_to_desc_from_is(path.d = "DESCRIPTION", imports = imports)
+              } else {attachment::att_to_desc_from_is(path.d = "DESCRIPTION", imports = imports, must.exist = FALSE)}'
         - Rscript -e 'remotes::install_deps(dependencies = TRUE)'
         - Rscript -e 'tinytex::install_tinytex()'
         - mkdir -p public
-        - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "{url}/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/master/download?job=pages" &&
-          unzip artifacts.zip &&
-          rm artifacts.zip &&
-          echo "copied master artifacts" ||
-          echo "copied master artifacts failed"'
-        - Rscript -e 'file.remove(list.files("public", full.names = TRUE))'
-        - Rscript -e 'unlink("public/libs", recursive = TRUE);unlink("public/images", recursive = TRUE)'
         - Rscript -e 'bookdown::render_book("index.Rmd", output_format = "bookdown::gitbook", clean = FALSE, output_dir = "public")'
         - Rscript -e 'bookdown::render_book("index.Rmd", output_format = "bookdown::pdf_book", clean = FALSE, output_dir = "public")'
+        - Rscript -e 'bookdown::render_book("index.Rmd", output_format = "pagedown::html_paged", clean = FALSE);file.copy("_main.html", "public/_pagedown.html")'
     artifacts:
         paths:
             - public
         expire_in: 30 days
-
-book-dev:
+        
+        
+book-main:
     stage: book-create
     only:
         - master
@@ -58,20 +54,62 @@ book-dev:
     script:
         - echo "Library path for packages :" $R_LIBS
         - mkdir -p $R_LIBS
+        - Rscript -e 'install.packages(c("remotes", "attachment", "tinytex", "usethis"))'
+        - Rscript -e 'if (!file.exists("DESCRIPTION")) {usethis::use_description()}'
+        - >
+          Rscript -e 'imports <- unique(c("bookdown", "knitr", "pagedown",
+            attachment::att_from_rmds(".", recursive = FALSE)));
+            if (packageVersion("attachment") <= "0.2.2") {
+              attachment::att_to_desc_from_is(path.d = "DESCRIPTION", imports = imports)
+              } else {attachment::att_to_desc_from_is(path.d = "DESCRIPTION", imports = imports, must.exist = FALSE)}'
         - Rscript -e 'remotes::install_deps(dependencies = TRUE)'
         - Rscript -e 'tinytex::install_tinytex()'
         - mkdir -p public
-        - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "{url}/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/production/download?job=pages" &&
+        - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/jobs/artifacts/production/download?job=pages" &&
           unzip artifacts.zip &&
           rm artifacts.zip &&
           echo "copied production artifacts" ||
           echo "copied production artifacts failed"'
-        # Clean dev directory
-        - Rscript -e 'unlink("public/dev", recursive = TRUE)'
-        - mkdir -p public/dev
+        - Rscript -e 'file.remove(list.files("public", full.names = TRUE))'
+        - Rscript -e 'unlink("public/libs", recursive = TRUE);unlink("public/images", recursive = TRUE)'
+        - Rscript -e 'bookdown::render_book("index.Rmd", output_format = "bookdown::gitbook", clean = FALSE, output_dir = "public")'
+        - Rscript -e 'bookdown::render_book("index.Rmd", output_format = "bookdown::pdf_book", clean = FALSE, output_dir = "public")'
+        - Rscript -e 'bookdown::render_book("index.Rmd", output_format = "pagedown::html_paged", clean = FALSE);file.copy("_main.html", "public/_pagedown.html")'
+    artifacts:
+        paths:
+            - public
+        expire_in: 30 days
+
+book-production:
+    stage: book-create
+    only:
+        - production
+    script:
+        - echo "Library path for packages :" $R_LIBS
+        - mkdir -p $R_LIBS
+        - Rscript -e 'install.packages(c("remotes", "attachment", "tinytex", "usethis"))'
+        - Rscript -e 'if (!file.exists("DESCRIPTION")) {usethis::use_description()}'
+        - >
+          Rscript -e 'imports <- unique(c("bookdown", "knitr", "pagedown",
+            attachment::att_from_rmds(".", recursive = FALSE)));
+            if (packageVersion("attachment") <= "0.2.2") {
+              attachment::att_to_desc_from_is(path.d = "DESCRIPTION", imports = imports)
+              } else {attachment::att_to_desc_from_is(path.d = "DESCRIPTION", imports = imports, must.exist = FALSE)}'
+        - Rscript -e 'remotes::install_deps(dependencies = TRUE)'
+        - Rscript -e 'tinytex::install_tinytex()'
+        - mkdir -p public
+        - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/jobs/artifacts/$CI_DEFAULT_BRANCH/download?job=pages" &&
+          unzip artifacts.zip &&
+          rm artifacts.zip &&
+          echo "copied $CI_DEFAULT_BRANCH artifacts" ||
+          echo "copied $CI_DEFAULT_BRANCH artifacts failed"'
+        # Clean production directory
+        - Rscript -e 'unlink("public/production", recursive = TRUE)'
+        - mkdir -p public/production
         # Keep clean to FALSE to retrieve intermediate files in case something fails
-        - Rscript -e 'bookdown::render_book("index.Rmd", output_format = "bookdown::gitbook", clean = FALSE, output_dir = "public/dev")'
-        - Rscript -e 'bookdown::render_book("index.Rmd", output_format = "bookdown::pdf_book", clean = FALSE, output_dir = "public/dev")'
+        - Rscript -e 'bookdown::render_book("index.Rmd", output_format = "bookdown::gitbook", clean = FALSE, output_dir = "production/dev")'
+        - Rscript -e 'bookdown::render_book("index.Rmd", output_format = "bookdown::pdf_book", clean = FALSE, output_dir = "production/dev")'
+        - Rscript -e 'bookdown::render_book("index.Rmd", output_format = "pagedown::html_paged", clean = FALSE);file.copy("_main.html", "public/production/_pagedown.html")'
     artifacts:
         paths:
             - public
@@ -85,7 +123,7 @@ pages:
         paths:
             - public
     only:
-        - master
         - main
+        - master
         - production
 
diff --git a/inst/gitlab-ci/check-coverage-pkgdown-renv.yml b/inst/gitlab-ci/check-coverage-pkgdown-renv.yml
--- a/inst/gitlab-ci/check-coverage-pkgdown-renv.yml
+++ b/inst/gitlab-ci/check-coverage-pkgdown-renv.yml
@@ -1,18 +1,18 @@
 image: {image}
 
 variables:
-  RENV_PATHS_CACHE: "/opt/local/renv/cache"
-  RENV_LOCAL_CACHE: "renv/library"
+  RENV_PATHS_CACHE: "cache"
+  RENV_PATHS_LIBRARY: "renv/library"
   GIT_DEPTH: 10
   REPO_NAME: "https://packagemanager.rstudio.com/all/__linux__/focal/latest"
-  R_LIBS: "ci/lib"
+  R_LIBS_USER: "ci/lib"
 
 cache:
   key: global-cache
   paths:
       - ${RENV_PATHS_CACHE}
-      - ${RENV_LOCAL_CACHE}
-      - ${R_LIBS}
+      - ${RENV_PATHS_LIBRARY}
+      - ${R_LIBS_USER}
 
 stages:
   - build
@@ -24,16 +24,22 @@ stages:
 building:
   stage: build
   script:
+    - if [[ $CI_DEFAULT_BRANCH == "master" || $CI_DEFAULT_BRANCH = "main" ]]; then echo "OK - Default branch is master or main"; else echo "Default branch is not master or main; please add yours ($CI_DEFAULT_BRANCH) where needed, as well as in the present line of code" ; exit 1; fi
     - apt-get update -qq && apt-get install -y libharfbuzz-dev libfribidi-dev
-    - echo "Library path for packages :" $R_LIBS
-    - mkdir -p $R_LIBS
+    - echo "Library path for packages :" $R_LIBS_USER
+    - mkdir -p $R_LIBS_USER
+    - mkdir -p $RENV_PATHS_CACHE
     - Rscript -e 'source("renv/activate.R")'
-    - Rscript -e 'renv::restore()'
     - Rscript -e 'install.packages("remotes")'
     - Rscript -e 'install.packages("rcmdcheck")'
+    - Rscript -e 'renv::restore()'
     - Rscript -e 'remotes::install_local(upgrade = "never")'
     - R -e 'rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")'
-
+  artifacts:
+      paths:
+          - check
+      expire_in: 30 days
+      
 # To have the coverage percentage appear as a gitlab badge follow these
 # instructions:
 # https://docs.gitlab.com/ee/user/project/pipelines/settings.html#test-coverage-parsing
@@ -46,11 +52,13 @@ coverage:
     when: on_success
     only:
         - master
+        - main
         - production
     script:
         - Rscript -e 'source("renv/activate.R")'
-        - Rscript -e 'renv::restore()'
+        - Rscript -e 'install.packages("remotes")'
         - Rscript -e 'remotes::install_cran(c("covr", "DT"), upgrade = "never")'
+        - Rscript -e 'renv::restore()'
         - Rscript -e 'covr::gitlab(quiet = FALSE)'
     artifacts:
         paths:
@@ -66,13 +74,15 @@ integration:
     when: on_success
     only:
         - master
+        - main
         - production
         - test-ci
     script:
         - Rscript -e 'source("renv/activate.R")'
+        - Rscript -e 'install.packages("remotes")'
+        - Rscript -e 'remotes::install_cran(c("pkgdown"), upgrade = "never")'
         - Rscript -e 'renv::restore()'
         - Rscript -e 'remotes::install_local(upgrade = "never")'
-        - Rscript -e 'remotes::install_cran(c("pkgdown"), upgrade = "never")'
         - Rscript -e 'pkgdown::build_site()'
     artifacts:
         paths:
@@ -87,12 +97,12 @@ integration-test:
         - test-ci
     script:
         - mkdir -p public/test
-        - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "{url}/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/master/download?job=pages" &&
+        - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/jobs/artifacts/$CI_DEFAULT_BRANCH/download?job=pages" &&
           unzip artifacts.zip &&
           rm artifacts.zip &&
-          echo "copied master artifacts" ||
-          echo "copied master artifacts failed"'
-        - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "{url}/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/production/download?job=pages" &&
+          echo "copied $CI_DEFAULT_BRANCH artifacts" ||
+          echo "copied $CI_DEFAULT_BRANCH artifacts failed"'
+        - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/jobs/artifacts/production/download?job=pages" &&
           unzip artifacts.zip &&
           rm artifacts.zip &&
           echo "copied production artifacts" ||
@@ -111,26 +121,27 @@ integration-production:
         - production
     script:
         - mkdir -p public/production
-        - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "{url}/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/master/download?job=pages" &&
+        - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/jobs/artifacts/$CI_DEFAULT_BRANCH/download?job=pages" &&
           unzip artifacts.zip &&
           rm artifacts.zip &&
-          echo "copied master artifacts" ||
-          echo "copied master artifacts failed"'
+          echo "copied $CI_DEFAULT_BRANCH artifacts" ||
+          echo "copied $CI_DEFAULT_BRANCH artifacts failed"'
         - cp -r docs/* public/production
     artifacts:
         paths:
             - public
         expire_in: 30 days
 
-integration-master:
+integration-main:
     stage: pkgdown-move
     dependencies:
         - integration
     only:
         - master
+        - main
     script:
         - mkdir -p public
-        - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "{url}/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/production/download?job=pages" &&
+        - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/jobs/artifacts/production/download?job=pages" &&
           unzip artifacts.zip &&
           rm artifacts.zip &&
           echo "copied production artifacts" ||
@@ -150,5 +161,6 @@ pages:
             - public
     only:
         - master
+        - main
         - production
         - test-ci
diff --git a/tests/testthat/gitlab-ci.yml b/tests/testthat/gitlab-ci.yml
--- a/tests/testthat/gitlab-ci.yml
+++ b/tests/testthat/gitlab-ci.yml
@@ -3,12 +3,12 @@ image: rocker/verse:latest
 variables:
   GIT_DEPTH: 10
   REPO_NAME: "https://packagemanager.rstudio.com/all/__linux__/focal/latest"
-  R_LIBS: "ci/lib"
+  R_LIBS_USER: "ci/lib"
 
 cache:
   key: global-cache
   paths:
-      - ${R_LIBS}
+      - ${R_LIBS_USER}
 
 stages:
   - build
@@ -20,13 +20,18 @@ stages:
 building:
   stage: build
   script:
+    - if [[ $CI_DEFAULT_BRANCH == "master" || $CI_DEFAULT_BRANCH = "main" ]]; then echo "OK - Default branch is master or main"; else echo "Default branch is not master or main; please add yours ($CI_DEFAULT_BRANCH) where needed, as well as in the present line of code" ; exit 1; fi
     - apt-get update -qq && apt-get install -y libharfbuzz-dev libfribidi-dev
-    - echo "Library path for packages :" $R_LIBS
-    - mkdir -p $R_LIBS
+    - echo "Library path for packages :" $R_LIBS_USER
+    - mkdir -p $R_LIBS_USER
     - Rscript -e 'install.packages("remotes")'
     - Rscript -e 'install.packages("rcmdcheck")'
     - Rscript -e 'remotes::install_local(upgrade = "never")'
     - R -e 'rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")'
+  artifacts:
+      paths:
+          - check
+      expire_in: 30 days
 
 # To have the coverage percentage appear as a gitlab badge follow these
 # instructions:
@@ -39,6 +44,7 @@ coverage:
     allow_failure: true
     when: on_success
     only:
+        - main
         - master
         - production
     script:
@@ -58,11 +64,13 @@ integration:
     allow_failure: true
     when: on_success
     only:
+        - main
         - master
         - production
         - test-ci
     script:
         - Rscript -e 'remotes::install_cran(c("pkgdown"), upgrade = "never")'
+        - Rscript -e 'remotes::install_local(upgrade = "never")'
         - Rscript -e 'pkgdown::build_site()'
     artifacts:
         paths:
@@ -77,12 +85,12 @@ integration-test:
         - test-ci
     script:
         - mkdir -p public/test
-        - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/master/download?job=pages" &&
+        - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/jobs/artifacts/$CI_DEFAULT_BRANCH/download?job=pages" &&
           unzip artifacts.zip &&
           rm artifacts.zip &&
-          echo "copied master artifacts" ||
-          echo "copied master artifacts failed"'
-        - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/production/download?job=pages" &&
+          echo "copied $CI_DEFAULT_BRANCH artifacts" ||
+          echo "copied $CI_DEFAULT_BRANCH artifacts failed"'
+        - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/jobs/artifacts/production/download?job=pages" &&
           unzip artifacts.zip &&
           rm artifacts.zip &&
           echo "copied production artifacts" ||
@@ -101,26 +109,27 @@ integration-production:
         - production
     script:
         - mkdir -p public/production
-        - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/master/download?job=pages" &&
+        - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/jobs/artifacts/$CI_DEFAULT_BRANCH/download?job=pages" &&
           unzip artifacts.zip &&
           rm artifacts.zip &&
-          echo "copied master artifacts" ||
-          echo "copied master artifacts failed"'
+          echo "copied $CI_DEFAULT_BRANCH artifacts" ||
+          echo "copied $CI_DEFAULT_BRANCH artifacts failed"'
         - cp -r docs/* public/production
     artifacts:
         paths:
             - public
         expire_in: 30 days
 
-integration-master:
+integration-main:
     stage: pkgdown-move
     dependencies:
         - integration
     only:
+        - main
         - master
     script:
         - mkdir -p public
-        - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/production/download?job=pages" &&
+        - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/jobs/artifacts/production/download?job=pages" &&
           unzip artifacts.zip &&
           rm artifacts.zip &&
           echo "copied production artifacts" ||
@@ -139,6 +148,7 @@ pages:
         paths:
             - public
     only:
+        - main
         - master
         - production
         - test-ci
